# Generated by Django 6.0 on 2025-12-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=190, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_propiedad', models.CharField(choices=[('CASA', 'Casa'), ('DEPTO', 'Departamento'), ('TERRENO', 'Terreno'), ('OFICINA', 'Oficina')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_asignadas', to='eva4.agente')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='eva4.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interesado', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='eva4.propiedad')),
            ],
        ),
    ]
